In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# concatenate（连接）

## 1、array的concatenate

In [3]:
arr1 = np.arange(9).reshape(3,3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr2 = np.arange(9).reshape(3,3)

In [6]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1,arr2],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

## 2、series的concat

In [8]:
s1 = Series([1,2,3], index=['X','Y','Z'])

In [9]:
s2 = Series([4,5], index=['A','B'])

In [10]:
s1

X    1
Y    2
Z    3
dtype: int64

In [11]:
s2

A    4
B    5
dtype: int64

In [12]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [13]:
pd.concat([s1,s2], axis = 1)

0    1
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN
A  NaN  4.0
B  NaN  5.0

## 3、dataFrame的concat

In [14]:
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [15]:
df1

X         Y         Z
0 -1.213775 -1.207585  0.116935
1 -1.205969  0.958269  1.198928
2 -0.252398 -1.498081 -0.852375
3 -1.292477  1.588582  0.461220

In [16]:
df2 = DataFrame(np.random.randn(3,3), columns=['X','Y','A'])

In [17]:
df2

X         Y         A
0  1.300477 -1.162462  1.693892
1  0.496495  1.240496  1.230561
2  0.919702  0.243632 -0.857741

In [18]:
pd.concat([df1,df2])

X         Y         Z         A
0 -1.213775 -1.207585  0.116935       NaN
1 -1.205969  0.958269  1.198928       NaN
2 -0.252398 -1.498081 -0.852375       NaN
3 -1.292477  1.588582  0.461220       NaN
0  1.300477 -1.162462       NaN  1.693892
1  0.496495  1.240496       NaN  1.230561
2  0.919702  0.243632       NaN -0.857741

In [19]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

# Combine

## 1、series

In [20]:
s1 = Series([2, np.nan, 4, np.nan], index=['A','B','C','D'])

In [21]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [22]:
s2 = Series([1,2,3,4], index=['A','B','C','D'])

In [23]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [31]:
s1.combine_first(s2)
# 用s2的value去填充s1

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

## 2、dataFrame

In [25]:
df1 = DataFrame({
    'X': [1, np.nan, 3, np.nan],
    'Y': [5, np.nan, 7, np.nan],
    'Z': [9, np.nan, 11,np.nan]
})

In [26]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [27]:
df2 = DataFrame({
    'Z':[np.nan, 10, np.nan, 12],
    'A':[1,2,3,4]
})

In [28]:
df2

Z  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [29]:
df1.combine_first(df2)

A    X    Y     Z
0  1  1.0  5.0   9.0
1  2  NaN  NaN  10.0
2  3  3.0  7.0  11.0
3  4  NaN  NaN  12.0